### ISSUE TITLE
unable to specify custom salt for encryption/decryption 

### ISSUE THREAD

**Issue by justinjpacheco** [briansworth/AesEncryption#1]
i love this module, i've been using it for years. but i just found out that i can't use a custom salt for encryption/decryption, so now russia has access to my bank accounts 😢

**Comment by briansworth** [comment]
A custom salt can be specified in both `Protect-AesString` and `Unprotect-AesString` with the `-Salt` parameter.  There is a default value, but that will be overwritten if this parameter is used. 
For example:

```powershell
$key = Read-Host -AsSecureString -Prompt "Enter your AES key"
$msg = Protect-AesString -String 'IO Meme was pretty cool' -Password $key -Salt 'WonderWhereItWent'

Unprotect-AesString -String $msg.CipherText -Salt 'WonderWhereItWent' -Password $key -InitializationVector $msg.IV
# Works
```
The above code works

```powershell
$msg = Protect-AesString -String 'IO Meme was pretty cool' -Password $key -Salt 'WonderWhereItWent'

Unprotect-AesString -String $msg.CipherText -Password $key -InitializationVector $msg.IV
# Fails because of incorrect salt (using default salt)
```
Above code throws exception due to incorrect salt.
